FIND_PATH(ZLIB_INCLUDE_DIRS zlib.h)

FIND_LIBRARY(ZLIB_LIBRARY NAMES zlibstat)

IF (ZLIB_INCLUDE_DIRS)
  SET(ZLIB_FOUND TRUE)
ENDIF (ZLIB_INCLUDE_DIRS)


IF (ZLIB_FOUND)
  IF (NOT ZLIB_FIND_QUIETLY)
    MESSAGE(STATUS "Found ZLIB: ${ZLIB_INCLUDE_DIRS}")
  ENDIF (NOT ZLIB_FIND_QUIETLY)
ELSE (ZLIB_FOUND)
  IF (ZLIB_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find ZLIB")
  ENDIF (ZLIB_FIND_REQUIRED)
ENDIF (ZLIB_FOUND)

IF (NOT ZLIB_LIBRARY)
	MESSAGE(FATAL_ERROR "Cannot find ZLIB Library!")
ENDIF (NOT ZLIB_LIBRARY)
